---
- name: Configure OSPF
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false


  tasks:
    - name: Configure OSPF
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: "{{ item.process_id }}"
              domain_id:
                ip_address:
                  address: "{{ item.domain_id.address }}"
              network: "{{ item.networks }}"
              passive_interfaces: "{{ item.passive_interfaces }}"
      loop: "{{ ospf_process }}"
