---
ospf_process:
  - process_id: 100
    domain_id:
      address: 1.1.1.1
    networks:
      - address: 1.1.1.0
        wildcard_bits: 0.0.0.255
        area: 0
    passive_interfaces:
      default: true
      interface:
        set_interface: false
        name:
          - Ethernet0/3
